# Generated by Django 5.0.7 on 2024-07-15 16:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания проекта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('short_description', models.TextField(help_text='Небольшое количество текста.', verbose_name='Краткое описание')),
                ('text', models.TextField(help_text='Основной текст с полным описанием.', verbose_name='Текст')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SendQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
