# Generated by Django 5.0.7 on 2024-07-16 15:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_gallery', verbose_name='Изображение на главной')),
            ],
            options={
                'verbose_name': 'Изображение на главной',
                'verbose_name_plural': 'Изображения на главной',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Вводить в формате день.месяц.год', verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(blank=True, help_text='Не обязательное поле. Вводить в формате день.месяц.год', null=True, verbose_name='Дата окончания проекта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text='Автоматически заполняемое поле. Не вносить изменения.', unique=True, verbose_name='Идентификатор URL')),
                ('short_description', models.TextField(help_text='Основные тезисы проекта, цели и краткая информация.', verbose_name='Краткое описание')),
                ('text', models.TextField(help_text='Основной текст с полным описанием.', verbose_name='Текст')),
                ('main_image', models.ImageField(help_text='Изображение-обложка для страницы проекта.', upload_to='main_projects_images', verbose_name='Титульное изображение')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SendQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', help_text='Если заявка обработа, выберите "Да".', max_length=255, verbose_name='Обработан?')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('subject', models.CharField(default='', max_length=255, verbose_name='Тема')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='Изображение')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='schooling.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Изображения проекта',
                'verbose_name_plural': 'Изображения проектов',
            },
        ),
    ]
