# Generated by Django 5.0.7 on 2024-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Не обязательное поле. Вводить в формате ХХ.ХХ.ХХХХ ', null=True, verbose_name='Дата окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Вводить в формате ХХ.ХХ.ХХХХ ', verbose_name='Дата начала проекта'),
        ),
    ]
