# Generated by Django 5.0.7 on 2024-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default=1, help_text='Изображение-обложка для страницы проекта.', upload_to='main_projects_images', verbose_name='Титульное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Основные тезисы проекта, цели и краткая информация.', verbose_name='Краткое описание'),
        ),
    ]
