# Generated by Django 5.0.7 on 2024-07-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0002_project_main_image_alter_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendquestion',
            name='subject',
            field=models.CharField(default='Тема не указана', max_length=255, verbose_name='Тема'),
        ),
    ]
