# Generated by Django 5.0.7 on 2024-07-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0003_alter_sendquestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendquestion',
            name='is_complete',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', help_text='Если заявка обработа, выберите "Да".', max_length=255, verbose_name='Обработан?'),
        ),
    ]
