# Generated by Django 5.0.7 on 2024-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0004_sendquestion_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendquestion',
            name='subject',
            field=models.CharField(default='', max_length=255, verbose_name='Тема'),
        ),
    ]
