# Generated by Django 5.0.7 on 2024-07-16 07:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_alter_sendquestion_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendquestion',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
