# Generated by Django 5.0.7 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0006_alter_sendquestion_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_gallery', verbose_name='Изображение на главной')),
            ],
            options={
                'verbose_name': 'Изображение на главной',
                'verbose_name_plural': 'Изображения на главной',
            },
        ),
    ]
