# Generated by Django 5.0.7 on 2024-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date', '-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
