# Generated by Django 5.0.7 on 2024-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.TextField(help_text='Вторая колонка таблицы на странице "О Нас".', verbose_name='Индикатор')),
                ('info', models.TextField(help_text='Третья колонка таблицы на странице "О Нас".', verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Фирменное (полное официальное) наименование банка на русском языке.', max_length=255, verbose_name='Полное наименование банка')),
                ('short_name', models.CharField(help_text='Сокращенное фирменное наименование банка на русском языке.', max_length=255, verbose_name='Сокращенное наименование банка')),
                ('address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('mail_address', models.CharField(max_length=255, verbose_name='Почтовый адрес')),
                ('correspondent', models.CharField(max_length=255, verbose_name='Корр. счет')),
                ('checking', models.CharField(max_length=255, verbose_name='Расчетный счет')),
                ('bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН / КПП')),
            ],
            options={
                'verbose_name': 'Реквизиты поддержки',
                'verbose_name_plural': 'Реквизиты поддержки',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='MassMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('full_name', models.CharField(help_text='Вводить через пробел с большой буквы.', max_length=255, verbose_name='ФИО сотрудника')),
                ('qualification', models.CharField(max_length=255, verbose_name='Образование / Квалификация')),
                ('experience', models.PositiveSmallIntegerField(help_text='Год начала работы в социальной сфере.', verbose_name='Стаж работы')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsefullLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
    ]
