# Generated by Django 5.0.7 on 2024-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.TextField(help_text='Вторая колонка таблицы на странице "О Нас".', verbose_name='Индикатор')),
                ('info', models.TextField(help_text='Третья колонка таблицы на странице "О Нас".', verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Данные страницы "О Нас"',
                'verbose_name_plural': 'Данные страницы "О Нас"',
            },
        ),
    ]
