# Generated by Django 5.0.7 on 2024-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answ', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
