# Generated by Django 5.0.7 on 2024-07-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
