# Generated by Django 5.0.7 on 2024-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('full_name', models.CharField(help_text='Вводить через пробел с большой буквы.', max_length=255, verbose_name='ФИО сотрудника')),
                ('qualification', models.CharField(max_length=255, verbose_name='Образование / Квалификация')),
                ('experience', models.PositiveSmallIntegerField(help_text='Год начала работы в социальной сфере.', verbose_name='Стаж работы')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
