# Generated by Django 5.0.7 on 2024-07-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefullLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='На сайте название не отображается, это поля для нас.', max_length=255, unique=True, verbose_name='Название')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка на ресурс')),
                ('image', models.ImageField(upload_to='usefull_link_image', verbose_name='')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutitem',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
    ]
