# Generated by Django 5.0.7 on 2024-07-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0004_usefulllink_alter_aboutitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefulllink',
            name='image',
        ),
    ]
