# Generated by Django 5.0.7 on 2024-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0005_remove_usefulllink_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulllink',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
