# Generated by Django 5.0.7 on 2024-07-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0006_alter_usefulllink_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка на ресурс')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['id'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
