# Generated by Django 5.0.7 on 2024-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0007_massmedia_alter_ourteam_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Фирменное (полное официальное) наименование банка на русском языке.', max_length=255, verbose_name='Полное наименование банка')),
                ('short_name', models.CharField(help_text='Сокращенное фирменное наименование банка на русском языке.', max_length=255, verbose_name='Сокращенное наименование банка')),
                ('address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('mail_address', models.CharField(max_length=255, verbose_name='Почтовый адрес')),
                ('correspondent', models.CharField(max_length=255, verbose_name='Корр. счет')),
                ('checking', models.CharField(max_length=255, verbose_name='Расчетный счет')),
                ('bik', models.CharField(max_length=255, verbose_name='БИК')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН / КПП')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
