# Generated by Django 5.0.7 on 2024-07-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_pages', '0008_charity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name': 'Реквизиты поддержки', 'verbose_name_plural': 'Реквизиты поддержки'},
        ),
    ]
